require("prog.plugins-setup")
require("prog.plugins.treesitter")
require("prog.plugins.lsp.mason")
require("prog.plugins.lsp.lspconfig")
require("prog.plugins.lsp.lspsaga")
require("prog.plugins.lsp.lspkind")
require("prog.plugins.lsp.lsp-colors")
require("prog.plugins.lsp.null-ls")
require("prog.plugins.nvim-cmp")
-- require("prog.plugins.colorizer")
require("prog.core.options")
require("prog.core.keymaps")
-- require("prog.core.colorscheme")
require("prog.core.gruvboxTheme")
-- require("prog.core.TokoyoTheme")
require("prog.plugins.comment")
require("prog.plugins.nvim-tree")
require("prog.plugins.staline")
require("prog.plugins.gitsigns")
require("prog.plugins.bufferline")
require("prog.plugins.telescope")
require("prog.plugins.autopairs")
require("prog.plugins.blankline-config")
require("prog.plugins.presence")
require("zen-mode")
